# Generated by Django 3.0.5 on 2020-04-27 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='abc@examplemail.com', max_length=100),
            preserve_default=False,
        ),
    ]
