# Generated by Django 3.0.4 on 2020-05-02 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_profile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='city',
        ),
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.TextField(default='Add your address here'),
        ),
        migrations.AddField(
            model_name='profile',
            name='contact',
            field=models.BigIntegerField(default='1234567890'),
        ),
        migrations.AddField(
            model_name='profile',
            name='profession',
            field=models.CharField(default='Responsible Citizen', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.IntegerField(default=18),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(default='Lets make some effort', max_length=150),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(default='Male', max_length=15),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(default='New User', max_length=50),
        ),
    ]
