# Generated by Django 3.0.4 on 2020-05-02 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200502_1539'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drives',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(default=' ', max_length=50)),
                ('Place', models.TextField(default=' ')),
            ],
        ),
    ]
